spring:
  application:
    name: quiz-service
  datasource:
    url: ${QUIZ_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD3}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
      format_sql: truec
    show-sql: true
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}

server:
  port: 8085
  address: 0.0.0.0