spring:
  application:
    name: ad-service
  datasource:
    url: ${AD_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
      format_sql: true
    show-sql: true
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}
  hikari:
    maximum-pool-size: 10       # 최대 커넥션 수 제한
    minimum-idle: 1             # 최소 유휴 커넥션 수
    idle-timeout: 30000         # 30초 이상 유휴 상태면 커넥션 반환 (ms)
    max-lifetime: 900000        # 5분 지나면 커넥션 교체 (ms)
    connection-timeout: 5000    # 5초 내에 커넥션 못 얻으면 예외 (ms)
    leak-detection-threshold: 5000

server:
  port: 8085
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true
